name: Build, Test, and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOTNET_VERSION: "7.0.100"
  BUILD_CONFIGURATION: Release
  FEEDZ_SOURCE: https://f.feedz.io/forevolve/fluentvalidation/nuget/index.json

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET Core ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build
        run: dotnet build --configuration ${{ env.BUILD_CONFIGURATION }}

      - name: Unit Test
        run: dotnet test --configuration ${{ env.BUILD_CONFIGURATION }}

      - uses: dotnet/nbgv@master
        id: nbgv
        with:
          setAllVars: true

      - name: Pack
        run: dotnet pack --configuration ${{ env.BUILD_CONFIGURATION }}

      - run: echo 'PublicRelease=${{ steps.nbgv.outputs.PublicRelease }}'

      - name: Push to feedz.io
        run: dotnet nuget push **/*.nupkg -k ${{ secrets.FEEDZ_API_KEY }} -s ${{ env.FEEDZ_SOURCE }}
        if: ${{ steps.nbgv.outputs.PublicRelease == 'false' }} #github.event_name == 'pull_request'


      # - name: Push to NuGet.org
      #   run: dotnet nuget push **/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
      #   if: github.event_name == 'push'
